### ISSUE TITLE
Hex dependencies error

### ISSUE THREAD

**Issue by machad0** [raphaklaus/gameboy-rom-visualizer#1]
Hello,

I'm facing this problem when I run `docker-compose run --rm elixir mix compile`:
![print](https://user-images.githubusercontent.com/6047882/31579844-a0d3b616-b115-11e7-9c23-f4bac884a3cd.png)

Anyway, If I follow these instructions from the error message above running ` docker-compose run --rm elixir mix deps.get` It builds hex internally and then I can run the `mix compile` normally.

Tested on Arch/Manjaro Linux 
docker-compose `v1.16.1`

**Comment by raphaklaus** [comment]
Merged!

As discussion:

I don't think 2 commands are good to run the script using Docker, also this technique stands on Docker container cache which can lead to unwanted behaviors. ASAP I will pass the `deps.get` part for a `Dockerfile` so it gets dependencies automatically when the container is started.

I'm leaving this issue open as a reminder.

Thank you for reporting it!

**Comment by machad0** [comment]
Ok, it Makes sense to me! 

I just opened that PR #3 as a proposal. Check it out later pls.

Btw, just noticed that I have to update the readme as well (if merged).

cheers

**Comment by raphaklaus** [comment]
Closed as the project has been changed to JS/TS.
